parameters:
  nav_items:
    non_logged:
      - id: 1
        name: "Home"
        link: "/"
      - id: 2
        name: "Sign in/up"
        link: "/sign"
      - id: 3
        name: "Create"
        link: "/create"
      - id: 4
        name: "Browse"
        link: "/browse"
    logged:
      - id: 1
        name: "Home"
        link: "/"
      - id: 2
        name: "Create"
        link: "/create"
      - id: 3
        name: "My Collections"
        link: "/my_collections"
      - id: 4
        name: "Browse"
        link: "/browse"
      - logout: "Logout"
        path: "/logout"

